// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv_7F6aADB4V09Lh2BvmNBDaP7AMjnS0U',
    appId: '1:48808032272:web:c90980ebd6479d9fb77295',
    messagingSenderId: '48808032272',
    projectId: 'shopping-cart-52f9b',
    authDomain: 'shopping-cart-52f9b.firebaseapp.com',
    storageBucket: 'shopping-cart-52f9b.firebasestorage.app',
    measurementId: 'G-KTB8G5GTZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDawwYEqJl84TNlE_jZoDnCVaCYALCDw-c',
    appId: '1:48808032272:android:88b8e665736f6d14b77295',
    messagingSenderId: '48808032272',
    projectId: 'shopping-cart-52f9b',
    storageBucket: 'shopping-cart-52f9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUMqPIwovqGQiSLEwDnAyn9qNPUgI9P8c',
    appId: '1:48808032272:ios:930d25ce03249546b77295',
    messagingSenderId: '48808032272',
    projectId: 'shopping-cart-52f9b',
    storageBucket: 'shopping-cart-52f9b.firebasestorage.app',
    androidClientId: '48808032272-de1a4udikg70n65c4tu5ijqpoq9bltm8.apps.googleusercontent.com',
    iosClientId: '48808032272-lof1fb824uio4nl592elbvaj60kc2f63.apps.googleusercontent.com',
    iosBundleId: 'com.rutva.shoppingCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv_7F6aADB4V09Lh2BvmNBDaP7AMjnS0U',
    appId: '1:48808032272:web:550547dc06f3d8cab77295',
    messagingSenderId: '48808032272',
    projectId: 'shopping-cart-52f9b',
    authDomain: 'shopping-cart-52f9b.firebaseapp.com',
    storageBucket: 'shopping-cart-52f9b.firebasestorage.app',
    measurementId: 'G-ZVWY2BL6K0',
  );

}